[package]
name = "gqldb-executor"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tokio.workspace = true
gqldb-schema = { path = "../schema" }
gqldb-storage = { path = "../storage" }
gqldb-mvcc = { path = "../mvcc" }
gqldb-index = { path = "../index" }
gqldb-vector = { path = "../vector" }
