name: gqldb-ci

on:
  push:
    paths:
      - "gqldb/**"
  pull_request:
    paths:
      - "gqldb/**"

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gqldb
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Rust tests
        run: cargo test

  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gqldb/sdk/python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run tests
        run: pytest

  typescript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gqldb/sdk/typescript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: "20"
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
